sudo: required
services:
  - docker 

before_install:
  - docker build -t kevindan22/podman-react -f Dockerfile.dev .

script:
  - docker run kevindan22/podman-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-048315960483"
  bucket_path: "docker"
  on:
    branch: master
access_key_id: $AWS-ACCESS-KEY
secret_access_key:
  secure: "$AWS-SECRETE-KEY"
